//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.Demo.Marketing.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketing
    {
        public int Id { get; set; }
        public string EmpName { get; set; }
        public string MarketerName { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
    }
}
